### ISSUE TITLE
Crash on Latest Version

### ISSUE THREAD

**Issue by MokahTGS** [Zkaface/TAIGA#1]
http://pastebin.com/59DQX3Md

**Comment by IdleGandalf** [comment]
Since I can't reproduce this one, neither in my dev environment (which isn't surprising) or on my test server, cloud you test it with the attached jar file (packed into a zip due github) again?

[taiga-1.0.1-dev.zip](https://github.com/Zkaface/TAIGA/files/369703/taiga-1.0.1-dev.zip)

**Comment by ConnorRowe** [comment]
That fixed the problem for me, thanks.
