### ISSUE TITLE
Modifier descriptions not showing properly.

### ISSUE THREAD

**Issue by StevenTheEVILZ** [Zkaface/TAIGA#11]
I don't know what causes this, so I can't really fix it. Works in certain conditions, doesn't work in my modpack.

![2016-07-20_19 17 05](https://cloud.githubusercontent.com/assets/13265529/17007508/059d61de-4eaf-11e6-8942-d33f5321605d.png)

**Comment by Zkaface** [comment]
This will be committed tomorrow, I already fixed that local :-)
