### ISSUE TITLE
Ore Spawning Request

### ISSUE THREAD

**Issue by Tenebris11** [Zkaface/TAIGA#12]
I would suggest increasing the spawn limits and spawning chance of your ores, since as it stands, they are _**extremely**_ rare.  I haven't been able to find a single piece of prometheum, but I need to find it since it is the only ore that you can mine after cobalt that can allow you to mine more ores later on.

**Comment by Zkaface** [comment]
I will just check this!

**Comment by Zkaface** [comment]
Ok this is a major bug! There SHOULD be prometheum, but there is not. It's fixed now. I will upload 1.0.3 later.
