### ISSUE TITLE
Balancing suggestion

### ISSUE THREAD

**Issue by Tenebris11** [Zkaface/TAIGA#15]
Sorry I'm suggesting a lot of things lately, I just want to help you guys out. 
I really think you guys should boost the stats of all your tools, since even the highest tier tools are only marginally better than manyullyn, making it barely worth it to get a material such as adamantite.

**Comment by Zkaface** [comment]
Hm, should also be configurable with a variable factor. Balancing is not so easy. Discovering the very best configuration for everyone is nearly impossible :-)

**Comment by vrork** [comment]
Also, another suggestion is making some ores (prometheum for exemple) more visible. They are almost impossible to see

**Comment by Zkaface** [comment]
@vrork -> fixed in 1.0.3

**Comment by Zkaface** [comment]
I will do a complete rework of the material integration including a complete rebalancing of the associated values (speed, attack, durability)

**Comment by Zkaface** [comment]
Duplicate with #28
