### ISSUE TITLE
Can't Repair

### ISSUE THREAD

**Issue by Gebcrafter** [Zkaface/TAIGA#17]
Im not sure if this is only me, since this is a huge issue and i havent seen it on github yet.
Using meteorite ingot to repair a meteorite-bladed broadsword
![2016-07-23_01 18 39](https://cloud.githubusercontent.com/assets/15183529/17075973/9d29decc-5073-11e6-98ef-cccc3e6cb6c8.png)

**Comment by StevenTheEVILZ** [comment]
@Gebcrafter mod list please?

**Comment by Gebcrafter** [comment]
@StevenTheEVILZ 
Since i dont want to spam the post, ill use pastebin
http://pastebin.com/CyR9R5gB
Versions are all latest.

**Comment by StevenTheEVILZ** [comment]
@Gebcrafter can I please also have a log?

**Comment by Gebcrafter** [comment]
Ok. The only thing i did was load up my world, get meteorite out of my EZStorage system, and try to repair my sword.
http://pastebin.com/vhLHaW3m

**Comment by Zkaface** [comment]
I am not able to reproduce this issue this as well. Are you able to repeat the process? Also it would be particularly interesting if this happens in combinations with other materials.

**Comment by StevenTheEVILZ** [comment]
I think I fixed it with the latest PR without knowing it. See TAIGA.java line 117: ".addItem(item, 1, Material.VALUE_Ingot)"
