### ISSUE TITLE
Ore gen

### ISSUE THREAD

**Issue by vrork** [Zkaface/TAIGA#18]
Hello!. A sugestion for ore gen balancing.
There is too many slagiron and slagold. Unless they have a unique purpose, i would suggest removing them since they are the same as iron and gold and just "clutter" inventories, so i see no point of them existing. If they do have a unique purpose, just tune down their gen a lot, beucause thei are far too common.

**Comment by Zkaface** [comment]
Will be implemented as config in 1.1 or earlier

**Comment by Redlotus99** [comment]
One thing you may consider adding is a whitelist/blacklist for dimensions. I have run a modpack for quite  a few years now and I have always used Aroma1997's Dimensional World which adds a flat mining world as Dimension 6. I am not seeing any ore gen in this dimension from TAIGA. I am also unsure what ores should be spawning in the overworld from TAIGA, but whichever mods spawn in the Overworld should be spawning in the mining dimension.

Is there a breakdown of where ores spawn? (Nether, End or Overworld)
Can you add a whitelist/blacklist for dimensions where the ores can spawn?

Appreciate all the work and any help you give.

**Comment by Zkaface** [comment]
Good Idea, @Redlotus99. I gonna speak about this with @IdleGandalf

**Comment by vrork** [comment]
@Redlotus99 To see wich ores spawn where its easy, just open the game and use JEI to see the ores from this mod. Its very easy.

**Comment by Redlotus99** [comment]
I'll double check JEI again and see if it shows it.

**Comment by Zkaface** [comment]
You'll see it, when you check the base textures. 

But to be straight: titanite, tiberium, palladium and prometheum are nether related and adamantite, rubium, ignitite and violium are end realted. Look in taiga.world.ZWorldGen

**Comment by Redlotus99** [comment]
Ah...so no ores spawn in overworld then. That's good to know.  I'm at work and unable to check JEI at the moment I appreciate the feedback.

**Comment by StevenTheEVILZ** [comment]
some ores spawn in the overworld, just not in stone (some are generated in andesite and others)

**Comment by Redlotus99** [comment]
Hmm, I'll double check my Mining World again. As I was not seeing any of the alloys spawning in the Mining world at all.  I use the mining world so the overworld doesn't turn into swiss cheese over a long time playing.

For reference, I reported it to Aroma1997 here:

https://bitbucket.org/Aroma1997/miningworld/issues/83/some-mod-ores-missing

**Comment by IdleGandalf** [comment]
@Redlotus99 Has that fixed that TAIGA ores are missing as well, or are they still missing? If so, it would be cleaner to open a separate issue for that as the one we are in now is about a different topic of ore gen.

**Comment by Redlotus99** [comment]
I'll open a separate ticket as I'm still not seeing them. Two other mods I use had the same issue and put in a fix. I'll post their code in the new ticket maybe it can help out.
