### ISSUE TITLE
Crash during init stage 1

### ISSUE THREAD

**Issue by ConnorRowe** [Zkaface/TAIGA#2]
Taiga-1.0
TConstruct-1.10-2.3.3a
forge-1.10.2-12.18.1.2014

I just added the mod to my pack and it crashes during initialisation. Here is the crash report:
[http://pastebin.com/vzRxrfM0](http://pastebin.com/vzRxrfM0)

**Comment by IdleGandalf** [comment]
If I'm correct about the cause of this crash this may be a dup of #1. Could you try the attached jar file in that issue and report back if that fixes your problem?

**Comment by IdleGandalf** [comment]
Fixed in version 1.0.1, should be released soon on CurseForge.
