### ISSUE TITLE
Ores not present in creative mode

### ISSUE THREAD

**Issue by Sethervan** [Zkaface/TAIGA#22]
It would be nice to have the ores available in creative mode so we can play around with the ores directly.  For now you can find ingots in creative mode but you can't place a block of ore so you can test the items.

**Comment by Zkaface** [comment]
I will implement this either in 1.0.3 or the following version :) Totally have forgotten it.
Thx

**Comment by Zkaface** [comment]
Implemented in 1.1 for Blocks and Items. Other stuff like tools you still get via creative tab of TiC.
