### ISSUE TITLE
No config file

### ISSUE THREAD

**Issue by Sethervan** [Zkaface/TAIGA#23]
Many other mods have a config file so you can modify the ore drop rate and other options.  Can we get a config file to modify those options?

**Comment by StevenTheEVILZ** [comment]
Working on it.

**Comment by StevenTheEVILZ** [comment]
Metals will have adjustable stats

**Comment by Sethervan** [comment]
Awesome.  I love the mod so far and can't wait to see how it develops.

**Comment by IdleGandalf** [comment]
ToDo for a working configuration:

- [ ] Implement forge configuration stuff
- [ ] add desired configuration options
- [ ] use them instead of hard coded stuff (if applicable)

**Comment by Zkaface** [comment]
Next step finished.
[x] Implement forge configuration stuff
[x] add desired configuration options
[] ~~use them instead of hard coded stuff~~ (removed, because specific multipliers implemented)
