### ISSUE TITLE
More and better traits!

### ISSUE THREAD

**Issue by Zkaface** [Zkaface/TAIGA#26]
We need more traits and better ideas for existing ones.

Best method would be to name them with one associated category (solide, ethere, arcane or ratio) and a tier from 1 to 4 or maybe higher.

**Comment by vrork** [comment]
I can only think on one at the moment. A metal that increases the speed of the swing recovery. Maybe a ethere metal or a metal that is considered more light.

**Comment by EnderiumSmith** [comment]
A material that does bonus damage against guardians. The secondary trait would be aquadynamic.

**Comment by Zkaface** [comment]
@EnderiumSmith please give me further informations. At this moment I cannot see the clue, that this trait would be set apart from regular bonus damage traits. Why exactly should a weapon just deal bonus damage to this entity? 

Regards and thanks

**Comment by EnderiumSmith** [comment]
@Zkaface 2 options:
 A) a material that works better in a aquatic environment, is not slowed by water(aquadynamic) and is more effective against sea creatures(entitys that can breath underwater).
B) a material related to thunder and lightning. It does bonus damage to creatures in water and a second bonus damage to aquatic creatures and slimes(but not magma cubes). Its secondary trait would be either fire aspect or a thunder kockback/stun.

**Comment by IdleGandalf** [comment]
I would like to close this issue and try to get a new issue for every trait suggestion on the go. This should help organizing issues better and don't mega-blob a issue thread.
