### ISSUE TITLE
support for common ores and alloys

### ISSUE THREAD

**Issue by Hypsellis** [Zkaface/TAIGA#27]
I had already suggested that on CurseForge, but I don't think that anybody saw my comment, so I repost it here. An awesome thing you could do is to add Tinker's Construct tools support for all common ores when a mod adds them like Copper, Tin, Silver, Lead, Zinc, Nickel, Plantinium, Aluminium, Chromium, Osmium, Iridium, Titanium, Tungstene... and alloys like Bronze, Steel, Brass, Invar, Electrum, Signalum, Cupronickel, Tungstensteel...

**Comment by StevenTheEVILZ** [comment]
Yes, that is what I'm working on! Wait about a week and a half, and it shall be done.

**Comment by Zkaface** [comment]
Wait Steve, I'm not sure, if this is an option for our mod. This request seems to be perfect for a standalone mod, because I can not handle updates from foreign mods which have no connection to TiC before, e.g. when they use a different ore dictionary

**Comment by Hypsellis** [comment]
What do you mean by a different ore dictionnary ? Normally all well coded mods registered their ores in the ore dictionnary. The idea would be to detect if a random mod register one the ore I said before and add a support for Tinker's Construct for this ore. If the mod doesn't register its ores, it's the problem of the mod, it's its dev who did the things bad, not you.

**Comment by IdleGandalf** [comment]
I think what he meant so say was that it would be hard to maintain something like that, besides overlapping with other mods would most certainly lead to much problems and a high update frequency, which would just "bloat" this mod unnecessarily, IMHO.

**Comment by Hypsellis** [comment]
If it's better and simpler to make a standalone mod, why not, it won't change a lot at the end. ;)

**Comment by StevenTheEVILZ** [comment]
@IdleGandalf @Zkaface I have programmed an option to exclude the tinker "module" if ingots are not present. I'll continue to develop that portion, but if you think it's a bad idea, then you can tell me. BTW I've included a way for people to add integration to meet their own needs so y'all won't be constantly spammed with requests to support X. I think it's a good idea to at least include the option for something like that, even if it's not the focus of the mod.

**Comment by Zkaface** [comment]
This could be useful. At least it's helpful.... Feel free to integrate this ;-)

**Comment by DRTR0** [comment]
TiCon already supports those metals, if you'd actually read their documentation. Are you talking about a mod that adds those metals to oregen? There's like 5 other mods doing that right now. Substratum, Base Metals, Fun Ores, etc. No need to re-invent the wheel. I like the original and unique metals TAIGA adds.

**Comment by StevenTheEVILZ** [comment]
Ore gen is something that probably won't be added, but if it is, it will test for other mods' ores before adding. This would also be true for the ingots, blocks, and tconstruct tooparts.

**Comment by Hypsellis** [comment]
Substratum, Base Metals...adds only new ores with anything wich go with (ingot, block, nugget, dust, plate, rod, gear...), but it doesn't add any support for the Tinker's Construct tools, it just adds a support for melting ores and make alloys.
What I meant was to add a support for Tinker's Construct tools depending of the ores added by other mods. There is no need to add all the ores and everything wich go with inside TAIGA.

**Comment by Zkaface** [comment]
I think what @IdleGandalf said is the main reason why this should be made in a separate mod.

**Comment by DRTR0** [comment]
@Hypsellis 

Tinkers has it's own tools and material traits for those metals already. If whatever mod you're using that adds those metals and it doesn't show up in Tinkers, then you should submit a bug report to that mod, because they aren't registering their ores properly in pre-init. 

http://tinkers-construct.wikia.com/wiki/Material_Stats

**Comment by StevenTheEVILZ** [comment]
@Hypsellis @Zkaface Tconstruct doesn't add support for things like copper, bronze, enderium, etc. Nothing will be added except the tconstruct tool stats and possibly molten fluid. I'll continue to work on the json implementation of metals, but will hold off on adding any more alloys than present.

**Comment by Zkaface** [comment]
@StevenTheEVILZ you know, this json implementation has to work together with the config I actually work on with @IdleGandalf

**Comment by StevenTheEVILZ** [comment]
Yes, I'm taking a look at the config right now.

**Comment by StevenTheEVILZ** [comment]
Can you quickly summarize what it does?

**Comment by Zkaface** [comment]
Tinker's construct - own integration of matrials:

  // Mod Integration fluids
  public static FluidMolten brass;
  public static FluidMolten copper;
  public static FluidMolten tin;
  public static FluidMolten bronze;
  public static FluidMolten zinc;
  public static FluidMolten lead;
  public static FluidMolten nickel;
  public static FluidMolten silver;
  public static FluidMolten electrum;
  public static FluidMolten steel;
  public static FluidMolten aluminum;

If other authors do not implement their materials in TiC it's their own decision. I will look forward for an additional integration mod, but this is no priority atm - especially not for TAIGA modification.
