### ISSUE TITLE
Reorganization of Ores

### ISSUE THREAD

**Issue by Zkaface** [Zkaface/TAIGA#28]
In reference to a reorganisation of my implemented Ores and their substantial behaviour of being useful at the late game I am planning to reorganisate them. They need a better hierarchy and a well planned tree of getting better traits and values.

I would like to hear from you what kind of order you would prefer and what kind of metal should be an ore ore an alloy! At a last step the system still should be used with two or maybe three categories (I prefer 4 but like to hear what you think about it). It should be still necessary to find the ores in specific places with a specific harvest-level.

Thanks and regards, Rob

**Comment by DRTR0** [comment]
Overworld: 
- Tier 1 Ores (iron tier tools with iron ore rarity)
- Tier 1 Alloys (required to mine tier 2 ores)
- Tier 2 Ores (diamond tier tools with gold/diamond ore rarity)
- Tier 2 Alloys (required to mine Nether ores)

Nether:
- Tier 1 Ores (slightly better than Overworld T2 alloys)
- Tier 1 Alloys (slightly better than Cobalt/Ardite, required to mine tier 2 ores)
- Tier 2 Ores (much rarer, slightly better than Manyulin (did I spell that right))
- Tier 2 Alloys (required to mine End ores)

End:
2 ores
1 alloy (best metal in game)


I haven't thought through this much, but this structure sounds nice.

**Comment by DRTR0** [comment]
By slightly better than ___, I don't mean just mining level, but stats like durability, attack, attack speed, etc.

**Comment by Zkaface** [comment]
Thank you - what I mostly prefer is a combination of entering different world more than just one time. That's why you actually find at least 3 Ores in every dimension and you need it for several harvest levels and tiers.

**Comment by Zkaface** [comment]
This should be a long-term process and I do not want to hurry with it.

**Comment by DRTR0** [comment]
Having an extra 8 ores that are all higher than vanilla seems a bit OP. A blend of vanilla equivalent and higher sounds more balanced. What would you need an ore 8x more powerful than Cobalt for?

**Comment by Zkaface** [comment]
Well, why is Cobalt stronger than diamond? Because it should be used in late game. And the higher the hardness level, the better are high tier traits. You should need time and patience to find enough of your destinated ores to make the tools you like to. That is and will be my main aim.

**Comment by StevenTheEVILZ** [comment]
@Zkaface I'm almost done with implementing metals by json. This will make your life easier. It should be done sometime this week.

**Comment by Zkaface** [comment]
This gonna be the rework of material integration, alloying and balancing. Please write comments directly to the google docs table.

https://docs.google.com/spreadsheets/d/1CFTodwoEn-mqAvAQk7y72EbGZIPcKwZyPl-1EaKW1rk/edit?usp=sharing

**Comment by Redlotus99** [comment]
I like that there is a continuation of alloys and ores after cobalt. It gives TiC a longer progression and also gives players more to mine.  Some things in 1.10.2 that I miss from 1.7.10 are Iguana's Tinkers Tweaks and Extra TiC which added numerous additions to TiC that were just great. I can work up some information to add to this if anyone is even slightly interested in that info.

On top of all this, you should setup the config files and the like to blacklist/whitelist ores in certain dimensions so that players with large modpacks like myself can tweak them when needed. I use Aroma1997's Dimensional World which basically allows my players to mine for ores they would find in Overworld, but not nether ores or end ores.  This allows my Overworld to not have to become swiss cheese so to speak and also allows me to reset the mining world if I introduce a new mod with new ores. 

Lastly, TAIGA is great and the players on my server love it. I can't wait to see what comes next and I'll work up some ideas I have and also get some ideas from my players and maybe that'll help.

**Comment by MakerTim** [comment]
Well, one thing that needs to change is the commonalty of ores from higher levels
or at leased the high there spawing, Vibranium everywhere from the first block i mined even

**Comment by Utildayael** [comment]
I play with RedLotus and agree with everything he said.

In current state, and this is just some feedback, the only reason I see to get the TAIGA ores and use the TAIGA pickaxes/etc is to DEAL WITH THE TAIGA ORES. It really sucks mining and running into a giant cluster of Meteorite, Vibranium, etc as even with the top tier TAIGA tools it is like slogging through a wall of obsidian. I would recommend dropping the hardness of some of the ores down a bit as it is terrible how long it takes to break most of your ores using a 20 speed pickaxe even with buffs from BM's Living Armor to mining speed AND the fast miner sigil running. It's even worse if you run into a wall of the stuff and want to take it out with a hammer which is generally < 10 speed, especially if you have silktouch on it.

Ore spawn rates can be cut in half easily and still be effective. I go mining and come back with multiple *stacks* of things like Meteorite as I'm running around just trying to find diamonds/iron/gold/lapis/redstone and other mod-specific items that spawn deep.

**Comment by IdleGandalf** [comment]
I think that comment just points on what #37 is all about, please try to keep the issues separated.

**Comment by IdleGandalf** [comment]
I'll close this for now since 1.2 just released and includes what this issue is all about. If You still think there is room for improvement (which of course there always is), then please open a new issue.
