### ISSUE TITLE
Ores not spawning in added Dimensions

### ISSUE THREAD

**Issue by Redlotus99** [Zkaface/TAIGA#29]
This is a new ticket as suggested in https://github.com/Zkaface/TAIGA/issues/18

In my Mining World (Dim 6) I am noticing ores are not spawning from TAIGA. I was also having this issue with two other mods ([Ebon Arts](http://minecraft.curseforge.com/projects/ebon-arts?gameCategorySlug=mc-mods&projectID=238874) and [Environmental Tech](http://minecraft.curseforge.com/projects/environmental-tech?gameCategorySlug=mc-mods&projectID=245453)) and those mods have fixed this issue by using the code at the bottom of this issue. I am also linking to the mod that creates the mining world as reference. I hope this helps.

Mining World mod: [Aroma1997 Dimensional World](http://minecraft.curseforge.com/projects/aroma1997s-dimensional-world)

Code fix for ore spawn from Environmental Tech Author:

//Change From This
switch(world.provider.getDimensionType()){
case OVERWORLD:
//Overworld Generation Here
break;
case NETHER:
break;
case THE_END:
break;
}

//To This:
switch(world.provider.getDimensionType()){
case NETHER:
break;
case THE_END:
break;
default :
//Overworld Generation Here
break;
}
}

**Comment by Redlotus99** [comment]
You are awesome. I appreciate this.

**Comment by IdleGandalf** [comment]
Fixed in e8976365a2c26347a2266713dc179b09466d085b. That fix will be in the next bugfix release once we collect enough stuff to make it worth releasing :package: :P
