### ISSUE TITLE
[1.10.2] Crash on init with version 1.0 and minor issues

### ISSUE THREAD

**Issue by Gepett0** [Zkaface/TAIGA#3]
Hello Zkaface,

I also get the crash on minecraft/forge init. Even with a clean install of 1.10.2 forge 2011 and only TC+Mantle+TAIGA.
Got it working with the dev-version.
Just took a quick look through JEI and all the ores you got for us.
Minor issues/suggestions:
*Lignite Ore => crusher recipe (e.g. Tinker I/O, Furnus, Ender IO ...) maybe?
*Fuelbrick and glimmercoal have changing burn times, seen 100-600 fast switching.
Fuelbrick in furnace has 200 burntime (told by JEI, untested), though needing items with 6000 burntime total; dont know what you wnated for glimmercoal, but 1600 (also from JEI) seem also to less
*Your iron nuggets aren't ore dicted, are they? Why not use minecraft iron nugget instead?
*I didn't find a recipe for Slaggold Ore to Slaggold Ingot in JEI, did i miss anything? (just smelting, like    slagiron?)
*Tiberium Ore smelts to 288mb in smeltery but only 2 nuggets in furnaces, intended?
*Likewise for all the other metals, they are smelting for 288mb in the smeltery but only 1 ingot in furnaces

Anyway, this seems like a real nice mod. Glad to see even more cool addons for TC.

Gepett0

**Comment by Zkaface** [comment]
- Lignite Ore : gonna check that, i'm not sure atm how the recipe is implemented there
- Fuelbrick should be randomized... I fix the low value and think about how to get good random values without jumping animation
- There is no iron nugget in Vanilla. I have an idea about this - not clear for the moment.
- Slaggold ore should should work properly. I gonna test this and fix it, if necessary!
- Tiberium ore is no "metal", so you need to refine these shards, thei're kind of instable

Thanks and regards. I'm open for more suggestions! :+1: 

Rob

**Comment by IdleGandalf** [comment]
The crash should be fixed with the latest release (1.0.1).

**Comment by Gepett0** [comment]
Hi,

gave the new version another try. No crashes so far ;-)
Haven't played vanilla for a long long time, already forgotten there are no iron nuggets, sorry :-D

Suggestions and issues incoming:

*Lignite Coal now has 2 items with different burn time, fuel brick still to low for the cost
*Slaggold Ore is oredicted as gold nugget, didn't find a recipe in JEI for the ingot however
*Add a nugget for every metal and alloy please, it's a pain with some of the recipes from TC that don't need an uneven (ingot wise) amount of fluids (e.g. 216mb) to get rid of the leftover fluids in the smeltery if not using a tank
*Remove the recipe to smelt the Tiberium Ore in furnaces because of instability?
*Remove smelting of metal ores in furnaces or decrease fluid amount in smeltery? Atm: Ore in furnace= 1 ingot, ore in smeltery= 2 ingots.

Gepett0

**Comment by Zkaface** [comment]
* Lignite : 3 Items, yes. It's a feature caused of the natural behaviour of not being clean at all.
* Slaggold Ore: Thank you, this was a real issue and will be fixed in 1.0.2
* I will look for it and look what TC is doing e.g. for cobalt or ardite.
* I gonna check what's the matter there and if my bottleneck does not run as i like to.
* Oh, did TiC remove them from the regular smelting process?! I thought this would be possible. Thanks, will be also fixed in 1.0.2

**Comment by Gepett0** [comment]
Hi again,
running TAIGA 1.0.2 atm.

> Lignite: 3 Items, yes. It's a feature caused of the natural behaviour of not being clean at all.

-Stilll got issues with the balancing of crafting costs of fuelbrick: u need 3 minecraft coal with 1600 burntime each (4800 burn time total) + 3 pieces of lignite ( 1200 burntime version = 3600 burntime) summarizing to 8400 while only providing 3200 itself.

> Slaggold Ore: Thank you, this was a real issue and will be fixed in 1.0.2

-Slaggold Ore still oredicted as nuggetGold, can be used as any nuggetGold e.g. Botania Sparks or EnderIO capacitor
-Slagiron also oredicted as nuggetIron

> I will look for it and look what TC is doing e.g. for cobalt or ardite.

-I guess you mena the nugget thing here? Then I'm fine ;-)

> I gonna check what's the matter there and if my bottleneck does not run as i like to.

-For tiberium? Did a quick test with only 4 tiberium ores:
mined with diamond pickaxe without any enchants yield me 9 shards, thats 6,25 nuggets with crafting recipe or 9 nuggets through smelting in furnaces ( missing balance here, remove smelting recipe?);
4 tiberium ores silk touched when smelted in furnaces give 12 nuggets or even 8 ingots when smelted in the TiC smeltery ( missing balance here too)
summary:
tiberium processing is unbalanced all the way, sorry to say :-(

> Oh, did TiC remove them from the regular smelting process?! I thought this would be possible. Thanks, will be also fixed in 1.0.2

-Noticed u removed the smelting in furnaces for all the metals, fine with that :-)

Thx for your hard work.
Grüße aus Deutschland :-D

**Comment by Zkaface** [comment]
* Lignite: Ok, good clue! This will be iterated in the next minor update!
* Slag-Metals: This is intended. Of course i will put it in the config for the upcoming enhancing update.
* The nuggets will come!
* Tiberium: I will create a table to calculate it around. 
* Furnaces: As you say!

ATM my aim is, to render items in "Materials and You" and the description in the part builders... that fucks me up a bit. And I'm not able to find a solution >_<

Machet joot, Danke! :)
