### ISSUE TITLE
Slagiron ingot smelting recipe 

### ISSUE THREAD

**Issue by IdleGandalf** [Zkaface/TAIGA#30]
![2016-08-03_02 00 01](https://cloud.githubusercontent.com/assets/4494131/17349449/1e998ec8-591e-11e6-91c4-ff70308ab8bc.png)

Reproduce: Use JEI (or similar) to show all usages of slagrion ore, and go to smelting.

**Comment by accessdenied0** [comment]
I guess it is because the output item is not valid. TAIGA doesn't add Iron-nuggets. But I guess you already knew that...

**Comment by Zkaface** [comment]
@accessdenied0 It actually adds iron nuggets. At least it should. Of course something's broken in the config of @IdleGandalf ?

**Comment by accessdenied0** [comment]
@Zkaface ,

That is strange because it clearly doesn't. The only Iron-nugget is from "Better with Mods" mod:
- http://puu.sh/qqIeq/74b94bc7d8.jpg 
- http://puu.sh/qqIeE/8fc291361c.jpg

and by looking throu your mod I wasn't able to locate one...
- http://puu.sh/qqIij/46e8b016f3.jpg

I also checked my config but there is no option to disable nuggets in special...

access_denied

**Comment by Zkaface** [comment]
Ah think I got it. If you have a mod, which already has oredicted ironNugget, my mod refuses to register another one. That causes, that the recipe wont use the other ironNugget recipe...

Look at [Items.java : LINE 119](https://github.com/Zkaface/TAIGA/blob/master/src/main/java/com/sosnitzka/taiga/Items.java) in my code.

Here is the recipe [ SmeltingRegistry.java : LINE 14 ](https://github.com/Zkaface/TAIGA/blob/master/src/main/java/com/sosnitzka/taiga/recipes/SmeltingRegistry.java)

If you have an idea for a workaround, that would be great. For the next two weeks I am finishing my bachelor thesis at university.

**Comment by Zkaface** [comment]
fixed @IdleGandalf  @accessdenied0 
[Commit 185](https://github.com/Zkaface/TAIGA/commit/fafde83d4cc77ba2af31d4eae1b731d748f229ed)

**Comment by accessdenied0** [comment]
Thank you! 

Do you mind If I look through your source to learn a bit about the new MCF 1.10 and TiC API?

**Comment by Zkaface** [comment]
I would be happy if so :) I still need help with traits, modifiers and stuff for milestone 1.2!
