### ISSUE TITLE
No crafting recipes for block to ingot, etc.

### ISSUE THREAD

**Issue by SPMoo66** [Zkaface/TAIGA#31]
There don't seem to be any crafting recipes to convert between blocks, ingots, and nuggets of materials, only Tinkers' casting. Please consider adding them if this is intended, as it is much more of an inconvenience than anything else.

(using version 1.1.1)

**Comment by Zkaface** [comment]
Thank you. I thought TiC did this by itself. 

Will be fixed in 1.1.2 or in the big upcoming 1.2.

**Comment by Utildayael** [comment]
Came to log same issue. Glad to see it's being fixed!

Cheers

**Comment by Zkaface** [comment]
Fixed in 1.1.2. You're welcome!
