### ISSUE TITLE
Reviving Trait Spawns Regular Skeleton from Wither Skeleton Kill

### ISSUE THREAD

**Issue by mkleiman312** [Zkaface/TAIGA#32]
I realize regular skeletons and wither skeletons share a type, so I understand why this happens, but I'm wondering if there's a way to code around this.  Given that Noctunyx alloy is pretty expensive to begin with (especially the Spectrum Dust, and you need a lot to make multi-ingot parts), it would be great if killing wither skeletons (or any mob, for that matter) spawned/revived an exact copy.

**Comment by Zkaface** [comment]
Thank you, great hint! 

I will look for a workaround!
