### ISSUE TITLE
#newtrait super Heavy (alloy Neutronium)

### ISSUE THREAD

**Issue by DJKinggo13** [Zkaface/TAIGA#33]
So the idea is a new Alloy called **Neutronium** 
-It's based on a neutron star, a very densely packed alloy (with Neutrons), making it the heaviest alloy. 
-It's made with Meteorite, Solarium & Adamantite (Galactic materials and/or maybe with a special material)
-This level of density gives this material a crazy high base durability and a very high mining level (maybe even the bridge between 8 and a possible 9th level?)

The catch is the new trait: **Super Heavy**

Super Heavy is basicly the reverse of Lightweight, it makes you get mining fatigue the longer you use it and needs a short break to recover back to it's original speed. The more you use it the worse the mining fatigue gets & the longer the recovery time is.

**Comment by Zkaface** [comment]
Great Idea! Indeed!

**Comment by Zkaface** [comment]
Implemented as a workaround. Not exactly like you said, but I think my interpretation should work well :)
