### ISSUE TITLE
Please rotate this texture

### ISSUE THREAD

**Issue by BBoldt** [Zkaface/TAIGA#36]
Looks really really weird, especially considering the stone background is also rotated. I think it would be better to have Lignite just be a slightly brownish coal ore. Would be more consistant.

![](http://i.imgur.com/VYbn0MU.png)

**Comment by Zkaface** [comment]
In 1.2, there will be just texture overlays, so this weird texture bug is fixed.

Feel free to change the texture via ressource packs up to then!

**Comment by IdleGandalf** [comment]
Lignite is no more, so this is closed with 1.2.
