### ISSUE TITLE
Configurable spawn weights and heights for all ores

### ISSUE THREAD

**Issue by BBoldt** [Zkaface/TAIGA#37]
This would be helpful, I don't really like the default values. It seems like there is too much of everything, and not in very special places.

Also, you should set up some restrictive defaults so the more powerful ores are more rare. Like, have some spawn only in the range of mountaintops, or way down at bedrock level under lava. Etc.

**Comment by IdleGandalf** [comment]
Spawn weights will be configurable in one of the next major releases. If and/or when there will be configuration options for spawn heights added is up to Zkaface.

**Comment by BBoldt** [comment]
Looking at the config, it looks like you do have config options for spawning rates. They are all set to 1.0 though. I'll have to play around with different values.

Would love to have the spawn height thing, and also the ability to enable/disable every ore from being spawned. I could always use a third party mod to set up custom heights and ore distribution.

**Comment by Utildayael** [comment]
Sounds like a good move. I'm with the OP, the ore spawn is REALLY heavy right now. I find that I have more meteorite than iron/gold most of the time. :)

Could probably cut it by 50% on the default and still be good.

**Comment by Zkaface** [comment]
Please look for the new version 1.2. at this moment, there is no configuration for setting the height or density, but i will put something similar back in again in maybe 1.2.1 or 1.2.2!

**Comment by Zkaface** [comment]
Spawn weight config implemented - set to zero for no spawn.
Spawn height not yet implemented, because there are too many variables.
