### ISSUE TITLE
[1.1.2] Crash in end with curvature trait

### ISSUE THREAD

**Issue by SPMoo66** [Zkaface/TAIGA#38]
Just killed the dragon in the end, trying to break some blocks on a server with an Astrium pickaxe, when server will crash (looks like it's due to curvature)

http://pastebin.com/5HK91Tw5

**Comment by Zkaface** [comment]
I will try to reproduce this error.

**Comment by SPMoo66** [comment]
For what it's worth, this did happen multiple times...
Here's the other crash report we got, not sure how different it is to you.

http://pastebin.com/T74nPUHx

**Comment by IdleGandalf** [comment]
I fixed this, it will be in the next bugfix release.

**Comment by SPMoo66** [comment]
Thank you!
