### ISSUE TITLE
Lignite block

### ISSUE THREAD

**Issue by MakerTim** [Zkaface/TAIGA#39]
Hey, last update you added blocks and nuggets for a lot of blocks
but Lignite blocks are still missing
could you add them?
and with the vanilla 10% free extra burn (coal block = 10 coal in burntime)

would be appreciated :)

**Comment by Zkaface** [comment]
Okay, but be patient, because i will add this not until 1.2 :)

**Comment by MakerTim** [comment]
take your time ;)
better a good fix than half t problem away

**Comment by IdleGandalf** [comment]
I think this should be "fixed" by 1.2, since there is no more lignite :). And there should be blocks for all metals.
