### ISSUE TITLE
Ore blocks take far too long to break with the improper tool

### ISSUE THREAD

**Issue by unascribed** [Zkaface/TAIGA#40]
When trying to build an underground base, you'll need to dig out a lot of space. Generally, you do this with iron or stone tools, and eat the break time for things that you don't need.

All vanilla ores, and most ores in other mods, are either breakable at stone tier or take only a few extra seconds to break when at the wrong tier. TAIGA ores seem to take multiple _minutes_ to break with an improper tool, which makes building underground bases an ordeal.

**Comment by IdleGandalf** [comment]
Since this is a balancing issue, Zkaface will handle this. Be aware that he hasn't much time to spare at the moment, so this may take a while.

**Comment by SephirothWS** [comment]
Balancing issue? Taking _ten minutes_ to break an ore block that's _quite common_ yet _quite useless_ ... is NOT my idea of proper balancing. These incorrect harvest level mining times need to be brought inline with other mods so building underground bases aren't a huge pain in the ass.

**Comment by IdleGandalf** [comment]
Like I said, its balancing, one way or another. It may be a bigger balancing issue, but since it's balancing after all I'm not going to touch it since Zkaface is the one with the master plan in this regard. Some patience is needed here, even if I can fully understand what a hassle it may be.

**Comment by accessdenied0** [comment]
I want to take this issue to add my issue, which is of course related to.

I get nuts with Vibranium. Not only the most Ores are too common (which is of course configurable), Vibranium takes it to a whole new level. With the normal generation (1.0 in config) the occurrence of this material is annoying high... on all high levels...

Just a Screen for demonstration: http://puu.sh/r8N1G/c4e14d72ea.png

But further more with a proper Mining-tool (Miningspeed 12 is very convenient) it takes AGES to break. 
So far I noticed a similar issue with Meteorite which is also annoyingly hard to break.

I like this mod a lot! It is very fun to play around with all these different materials!

Please don't take this offensive and thank you for reading it.

**Comment by Zkaface** [comment]
No no, no need for excuses ;-) I had just about zero time to get on with the big upcoming update. But be assured, the balancing of power, abilities and generation will be much much better.

**Comment by accessdenied0** [comment]
@Zkaface ,

I wish I could be a better help. Thank you for this mod.

**Comment by SephirothWS** [comment]
@Zkaface Would this mean _proper balancing_? ... Like ores requiring cobalt or better being in the Nether and/or the End only? That would make things so much more ... well, ... non-tedious, for sure. Are we still going to have ores that even with the right mining level and a pretty fast speed, still seem to take ages to break? I mean, I don't mind the fact you're adding additional mining levels to your ores, but in the current state the mod is, your materials don't provide any mining speed boosts, so it feels like one is mining obsidian when it comes to your ores.

**Comment by Zkaface** [comment]
I gonna try to implement them more TiC like. What I am not sure with is the tier system. When should a material be more powerful or which speed or durability should be used... Questions. Lot of questions ;-)

**Comment by IdleGandalf** [comment]
Since 1,.2 is live now, could you verify that this is still an issue?

**Comment by SephirothWS** [comment]
This is indeed still an issue. If you happen to come across a TAIGA ore and don't have the correct tool, and even sometimes you DO have the correct tool, the block hardness is still quite high and/or next to impossible to break within any proper timing. The block hardness for pretty much *any* block in TAIGA is far too high. I can understand wanting to add additional mining levels, but you should NOT penalize the player with a near-bedrock like block just because their tool isn't at the correct mining level.

In the following video, I had spawned in the various "ores" and a block from the mod, (LOTS of localization errors still, that's another issue that should be in its own report.) ... and I tested mining them with an incorrect mining level tool, as well as the correct mining-level tool for some blocks. This is what the issue is about. This whole "rebalancing" according to the 1.2 changelogs on Curse doesn't actually fix this problem.

https://dl.dropboxusercontent.com/u/17518697/ShareX/2016/12/2016-12-06_19-39-07.mp4

**Comment by Zkaface** [comment]
@SephirothWS Names are not ready yet. It's a beta, I set the focus on bugs. Naming the stuff comes later! 

What happens, when you try to mine cobalt /ardite with iron? Isn't it the same - takes a long time to break a block without dropping its entity

**Comment by Zkaface** [comment]
@SephirothWS  @unascribed Block values (e.g. Hardness and Resistance) reduced to a normal value (except from some special materials). I've put in a value in config for giving these materials also "normal" values :)

@accessdenied0  The generation is now reduced, but i am not sure if it's low enough. Actual I work on ingame-wiki with the tinker book for more informations!
