### ISSUE TITLE
crash on startup ;-;

### ISSUE THREAD

**Issue by iluvdemomanandjunkrat** [Zkaface/TAIGA#43]
[crash-2016-09-12_18.57.46-client.txt](https://github.com/Zkaface/TAIGA/files/467228/crash-2016-09-12_18.57.46-client.txt)

**Comment by IdleGandalf** [comment]
That's a dup of #42. If you want TAIGA to work with TCon 2.5 you need to use TAIGA 1.1.3, which is available on CurseForge.
