### ISSUE TITLE
NoSuchFieldError with TConstruct

### ISSUE THREAD

**Issue by mobehun** [Zkaface/TAIGA#44]
With TConstruct 2.5.0 and TAIGA 1.1.3 I get this crash: http://pastebin.com/pikcXu3p
And with TAIGA 1.1.2 I get this: http://pastebin.com/cEjzvAiX
forge: 12.18.1.2077

With TConstruct 2.4.0 and TAIGA 1.1.2 it works fine.

**Comment by IdleGandalf** [comment]
@mobehun You are still using TAIGA 1.1.2 in the first crash. Please try 1.1.3 with TCon 2.5

**Comment by mobehun** [comment]
Yes. Sorry, At that point I was not sure who did what.
