### ISSUE TITLE
Incompatible with TiC 1.10.2 2.52

### ISSUE THREAD

**Issue by NillerUdenDild** [Zkaface/TAIGA#47]
Hey Zkaface.

TAIGA 1.10.2 1.1.2 is incompatible with Tinkers' Construct version 1.10.2 2.52, as stated in the changelog for TiC, found here: https://minecraft.curseforge.com/projects/tinkers-construct/files/2330969

Here's the crashlog:
[crash-2016-09-29_18.14.11-client.txt](https://github.com/Zkaface/TAIGA/files/501388/crash-2016-09-29_18.14.11-client.txt)

I hope this helps, and thank you for a nice mod :)

**Comment by IdleGandalf** [comment]
Thats why we released version 1.1.3, which has compatibility with latest tinkers.

If you find new issues with version 1.1.3 then please open a new issue, otherwise this is a dup of #42, #43, #44, #45.

**Comment by NillerUdenDild** [comment]
Ah I'm  sorry, I didn't realize there was a "closed" tab until now. Thanks for the swift reply though!
