### ISSUE TITLE
[1.1.4] Arcanite block has a higher mining level than the ore

### ISSUE THREAD

**Issue by SPMoo66** [Zkaface/TAIGA#52]
Ore has a mining level of Meteorite.
Block has a mining level of Vibranium.

I always thought that having the material blocks with high mining levels was questionable, but I think this is a bit too much.

**Comment by IdleGandalf** [comment]
That doesn't sound right, I will get in touch with @Zkaface and if it turns out to be a bug it will get fixed in the next bugfix release.

**Comment by Zkaface** [comment]
This is noticed. Caused of the complete overhaul of the ore implementation this error should be fixed in 1.2

**Comment by IdleGandalf** [comment]
Fixed in 1.2.
