### ISSUE TITLE
Materials from the old ExtraTiC and Compatibility with Other Mods

### ISSUE THREAD

**Issue by SirUmnei** [Zkaface/TAIGA#54]
Would be amazing if we could get some of the old ExtraTiC Mats (Fairy, Pokefennium) and compat with mods such and EnderIO, BiomesO'Plenty and maybe even introduce materials from ThermalExpansion, like Enderium, Lumium and Signalum.

**Comment by Zkaface** [comment]
The problem is: If i implement these materials and there is a missing mod, my work is useless. 

On other hand: What was the ability of "Fairy" and "Pokefennium" (in my opinion fairy sounds like a german dish soap :D )?

**Comment by SirUmnei** [comment]
If I remenber correctly, they didn't actually have a "special" trait, since in 1.7 they were very limited. I could come up with one if you want, but I need some time to think a bit.

I also understand what you mean that if the mod is missing you job is useless. Perhaps make an add-on to your own mod to add those? Not sure.

**Comment by Zkaface** [comment]
@SirUmnei Wether I implement Pokefennium or not - I need a lot more traits for 1.2! And if I say a lot I mean a huge amount... 

So, I WILL do that implementation of other mods, but just after release of 1.2. And that has priority at first ;)

**Comment by Zkaface** [comment]
@SirUmnei Please open another issue with informations about your desired traits and modifiers!
