### ISSUE TITLE
Cross-compatibility bug with ? (ores generation)

### ISSUE THREAD

**Issue by Hypsellis** [Zkaface/TAIGA#56]
I discovered a really strange bug with taiga ores. When I create a world, the taiga ores generate them normally. But if I leave the world and then reload the it, all the taiga ores are replaced by random vanilla Minecraft blocks (cake, pumpkin, glass, jukebox, fence, ender portal frames...). In more the FPS lower a lot. I have absolutely no ideas from where come this bug.

**Comment by Zkaface** [comment]
In that case we need your console output. Please repeat this issue and copy all the text with errors, loaded mods and stuff after appearing of this weird issue. Thx

**Comment by Hypsellis** [comment]
Here is the full log, good luck for finding what you want inside this mess. ^^'
[logs.zip](https://github.com/Zkaface/TAIGA/files/573974/logs.zip)
And here some pictures of the bug.
![2016-11-06_18 11 42](https://cloud.githubusercontent.com/assets/17103411/20039921/8b9fd8f4-a44d-11e6-8815-5e2897e07cf0.png)
![2016-11-06_18 12 03](https://cloud.githubusercontent.com/assets/17103411/20039923/8bac2fb4-a44d-11e6-8a0d-90ba16be2bdc.png)
![2016-11-06_18 13 23](https://cloud.githubusercontent.com/assets/17103411/20039924/8bb7b5c8-a44d-11e6-980e-6f20a2c9be9f.png)
![2016-11-06_18 13 31](https://cloud.githubusercontent.com/assets/17103411/20039925/8bbf8a96-a44d-11e6-8e6c-530da3a62141.png)

**Comment by Zkaface** [comment]
@Hypsellis Please put it in pastebin or something similar. I do not download zip files for logs :-)

**Comment by Hypsellis** [comment]
Sadly I'm not sure if I will be able to put all the log in pastebin so much it's big.

**Comment by IdleGandalf** [comment]
It's okay, I had a quick look at the logs, could you test if this still happens only with TAIGA and TConstruct loaded? You have quite a long list of mods there, a cross-compatibility bug is most likely, since we haven't seen that behavior in our tests so far.

**Comment by Hypsellis** [comment]
Sorry I can't put all the log inside pastebin, it's just too big. I ca still send you a file. [fml-client-latest.txt](https://github.com/Zkaface/TAIGA/files/574090/fml-client-latest.txt)

**Comment by Hypsellis** [comment]
Damn it's a crossmod bug, oh god it will take me many days if I have to searsh what is the other mod which provocate this bug. :(

**Comment by IdleGandalf** [comment]
Start with the ones who do have worldgen or manipulate worldgen in any way, like RetroGen (as example). If you should came across the one that's causing this you could give as a hint here, maybe we can do something about it, but it could be a bug in the other mod as well. I'm closing this for now, feel free to inform us if you got anything on this.

**Comment by Hypsellis** [comment]
I have 200 mods to test, it will take me many time before to know where come the bug.

**Comment by IdleGandalf** [comment]
That's true, but not all of them do wordgen, most likely the ones that don't have wordgen are not the cause.

**Comment by Hypsellis** [comment]
Yeah surely, but I have many worldgen mods. ^^'

**Comment by Hypsellis** [comment]
I think that it's something that mess with the save of the world.

**Comment by Hypsellis** [comment]
I made many tries by testing with little group of mods and trying it with all the mod of modpack, and I still didn't find what causes this issue. It means that surely more than 2 mods are linked to this issue.

**Comment by IdleGandalf** [comment]
Did it happen with the smaller pack as well? Do you mind sharing a list, maybe I'll get an idea on whats causing it when the mod list is a little smaller.

**Comment by Hypsellis** [comment]
No it's what I just said, I haven't been able to reproduce the issue by trying smaller packs.

**Comment by IdleGandalf** [comment]
Oh okay, that was not completely clear. That's odd but somewhat expected, it mayb be your best bet to drop them in one by one, and see if it works. That may be your best choice of narrowing down the exact cause (if there is one to begin with).

**Comment by Hypsellis** [comment]
In this case it will take me a huge time for finding the cause of the issue. Anyway I have enough for today, it makes 3 hours that I work on it. I will try it another day.

**Comment by Hypsellis** [comment]
It it can help, I toket only the world loading and unloading log, maybe you will find what you researsh inside. 
[world loading log.txt](https://github.com/Zkaface/TAIGA/files/574246/world.loading.log.txt)
[world unloading log.txt](https://github.com/Zkaface/TAIGA/files/574247/world.unloading.log.txt)

**Comment by Hypsellis** [comment]
I still researsh what is the causes of the issue, but I noticed that when I tried to create restored all the config folder, Minecraft was fucking slow (1 fps), but when I keep my current config, everything come back to the normal. 
I noticed too that placing any taiga ores in the corrupted worlds will replace them by another block, the ones. And each ores have his other block counterpart.
I think that all these bugs are linked. I hope I will find the cause of this issue soon.

**Comment by Hypsellis** [comment]
FuturePack seems to be the source of the bug, but there is surely another mod involved, anyway I can confirm that this one is involved to this issue.

**Comment by Hypsellis** [comment]
Oh god there is 4th mod involved in the bug, anyway forestry is involved in the bug too. I have to find the 4th mod now. Frankly this bug is really the strangest I ever seen. It will we be definitely not a simple one to solve.

**Comment by mcenderdragon** [comment]
OK thanks to @Hypsellis I am here :) @mezz you should look into this aswell as it seems Forestry is also somehow causing this. 
My first asumtion whould be: this is forge related, because we had a similar porblem wich a world save, we removed a mod and all Blocks got be replaced, but it turns out this was a desync from cleint and server (the server had it right but at the client the ID were mixed)

**Comment by Hypsellis** [comment]
I still researsh the 4th mod involved, but I think there is even a 5th one. I will try to give the most of informations as possible.

**Comment by Hypsellis** [comment]
Railcraft seems to be involved to the issue but inderectly. It doesn't replace all the TAIGA ores, but it makes the things worst. This is the 4th mod involved, but I'm close to find it. The thing I'm sure now, it's that there are more than 4 mods involved, and it seems to involve only big tech mods.

**Comment by Hypsellis** [comment]
The 4th mod involved is IndustrialCraft, there are another ones. The bug only happens with a really particular combinaison of mods that I try to find.

**Comment by Hypsellis** [comment]
Another mod involved, Applied Energetics.

**Comment by mezz** [comment]
I'm happy to help if Forestry is really an issue, but you are naming very large and well established mods as problems. Are you sure it's not an issue with any mod that adds ore generation and with TAIGA? You can have all those mods running without TAIGA and there is no issue.

**Comment by Hypsellis** [comment]
Yes everything goes right without TAIGA. I think that one of this mod do something wrong with the ore generation and world saving, something which override something else. 
But I'm not a modder of all these mods, I haven't any ideas of how there are coded, and what could provocate this issue. I just try to see which mods are involved in this issue.

**Comment by Hypsellis** [comment]
I just come to this conclusion like surely many other people here that TAIGA is the source of this issue. TAIGA does something wrong with ore generation and/or world saving. Something that other mods that add a lot of stuff to the world generation like tech mods or mods like BiomesOPlenty, AbyssalCraft or Quark don't like at all.

**Comment by mcenderdragon** [comment]
@Hypsellis if you mine the Blocks, drop they as the block the should be (taiga ore) or drop they as wrong vanilla block

**Comment by Hypsellis** [comment]
They drop them as the wrong block, they are really totally replaced. After when I place a TAIGA ores block and mine it, I get the good ore, but the particle of droping are the ones of the wrong block. If I add any new TAIGA ores block to the world, and then reload it, they are replaced too. The wrong blocks aren't necessarily vanilla blocks, it can be blocks from any mods, and they seem to change at each new worlds. But the same ore is always replaced by the same block.

**Comment by Zkaface** [comment]
@Hypsellis And this just happens with Taiga Blocks?

**Comment by mezz** [comment]
Sounds like either the blocks are only registered on the client, or only placed on the client for worldgen.

**Comment by Hypsellis** [comment]
I recently finded it happens too with SaltyMod blocks that are replaced with random Tinkers Construct blocks in the same way than Taiga ores. But strangely in this case they are always replaced by Tinkers Construct block.

**Comment by Zkaface** [comment]
@mezz This is what I thought about it. @Hypsellis does it happen just in multiplayer or even in singleplayer?

**Comment by mezz** [comment]
One possibility is that something in your block crashes on a server from being marked client-side only. If you are catching and suppressing exceptions too liberally it may never make it to the log.

However I'm just guessing based on some past experience. Let me know if you run out of ideas.

**Comment by Hypsellis** [comment]
It happens in singleplayer too.

**Comment by Zkaface** [comment]
I am not able to reproduce this issue, so it must be related to another mod. 

Does it only happen with generated ores or also with manually placed blocks?

**Comment by mezz** [comment]
There goes my theory. 
Best strategy is probably to reduce the mods until you find a small number that have the problem.

**Comment by Zkaface** [comment]
Ide: Start a developement workspace with 50% of the mods + TAIGA. If it works, take the other half of the mod list. Then reduce it again by 50% and on and on.

**Comment by mezz** [comment]
Looking at the log, I think this mod is the primary suspect for this issue:
`[17:55:27] [main/INFO] [FML/]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from NotEnoughIDs-1.5.0.jar`

**Comment by Zkaface** [comment]
Possible!

**Comment by Hypsellis** [comment]
Manually placed block are fine when I place them, but when I reload the world, they are replaced too.

**Comment by Hypsellis** [comment]
It could be an issue with NotEnoughId. I use it because my modpack goes beyond the forge block id limit.

**Comment by Zkaface** [comment]
ID Limit is a Thing! This might be it... But I am not sure

**Comment by Hypsellis** [comment]
I'm not sure neither...

**Comment by P3rf3ctXZer0** [comment]
First how do you have 200 mods and function at all! Second I use NotEnoughIds and have no problems. Try rebuilding all your configs and then your world. Also please give me your modlist and I will try and deduce the situation. I have over 12000 block ids without any hangups XD

**Comment by Zkaface** [comment]
@P3rf3ctXZer0 The real mvp

**Comment by P3rf3ctXZer0** [comment]
@Zkaface lol thanks I just don't like when a mod is wrongly accused XD Especially one I helped debug from day one.

**Comment by mezz** [comment]
Suspected and accused are not the same. You might as well start an investigation with whatever looks most likely.

**Comment by Hypsellis** [comment]
I don't accuse anybody, I try to help and find a solution. I already rebuilt all the config and reinstalled everything, nothing changes. Anyway if you want to help, you're the welcome. If you want to know the mod list I play with, you can find it here : http://www.modlister.com/user/Hypsellis. If you want I can send you the archive of my modpack.

**Comment by P3rf3ctXZer0** [comment]
Okay the issue at least in part is UniDict. I had the same problem with that mod recently. 
Here is a broken pack but even more broken by UniDict.
https://www.dropbox.com/s/26vaaym6i3f8lre/Death%20Plague%20Gaming%20-%20Rebooted-r1-f3.zip?dl=0

**Comment by Hypsellis** [comment]
I removed UniDict from the modpack, and it doesn't change anything. I had already tried before. So please stop to tell wrong things, you really don't help.

**Comment by Hypsellis** [comment]
This issue could maybe be linked to this one http://bt.industrial-craft.net/view.php?id=1869. I noticed that this crash happened often when travelling the world durring chunck loading in a reloaded world, exactly in the same than how the TAIGA and SaltyMod ore bug happens. And IndustrialCraft is linked to the issue since the issue doesn't happen when it's not present

**Comment by Hypsellis** [comment]
I discovered something too, only the ores under the 60 layer are replaced, all the others adove it stays fine.

**Comment by P3rf3ctXZer0** [comment]
Geez sorry. 90% of your mods are not in my pack. So if its not UniDict and its Not NotEnoughIDS than what could it be?

**Comment by Hypsellis** [comment]
No it's not UniDict, it could be NEI, but not sure.

**Comment by Hypsellis** [comment]
The problem seems to have been solved, it came indeed from NEI. So I close this issue for the time. Anyway thanks to you all for having helped to find the source of this issue ^w^
