### ISSUE TITLE
Possible bug after insatiable hit

### ISSUE THREAD

**Issue by Seiklus** [Zkaface/TAIGA#57]
[image of the shuriken](http://i.imgur.com/eCaeldi.png)
shuriken with Tiberium, Obsidian, and Manyullyn.
What to do: create a shuriken with 2 manyullyn, 1 tiberium, and 1 obsidian knife piece. throw at enemies until crash,usually when an explosion happens.
crash log: [here](http://pastebin.com/Yy3PJ0zx)

**Comment by IdleGandalf** [comment]
Thanks for reporting this. Is fixed and will be included in the next bugfix release.
