### ISSUE TITLE
Crash with Simple Tcon (TiC limitation)

### ISSUE THREAD

**Issue by TheOldOne822** [Zkaface/TAIGA#58]
This is a limitation with TiC itself and I'm looking into a workaround on my end but I felt it should reported here too so you would be aware of it.

Both Simple Tcon and TAIGA add Mythril to TiC and unfortunately if two mods try to add materials with the same name TiC will crash.

https://github.com/TheOldOne822/SimpleTcon/issues/2

**Comment by IdleGandalf** [comment]
That's good to know indeed. If I'm not mistaken, wouldn't it be enough to check for a existing material with that name before registering? I mean, we could do that, that should restore compatibility with Simple Tcon, wouldn't it? (at least if you do the same thing ofc)

**Comment by TheOldOne822** [comment]
That should work if done on both ends and I'm planing on doing that for the next update. 
I still plan to try to find a workaround as it's likely there could be other overlaps with other mods that may not check.

**Comment by IdleGandalf** [comment]
I wonder if the folks over at TCon are aware of that, I mean double registering materials is a whole different story, but that crash seems a little odd.

Whatever, I'll include a check in the next update as well, but like you said, it is just a workaround, not a good solution indeed.

**Comment by Zkaface** [comment]
In 1.2 I will replace Mythril with another ore. I know that this is not the best scenario, because who tells me that there won't be other ores with this or that name. But this is also the last time I will do this. The main problem is that other materials should have the same mining level and hardness and is it lore friendly.

**Comment by IdleGandalf** [comment]
I fixed this in PR #60, as sonn at thats gets merged and 1.2 is released this will be fixed.

**Comment by charlesbevans** [comment]
You could just spell it mithril or mithrill.

**Comment by IdleGandalf** [comment]
1.2 just hit CurseForge, so I'll close this now.
