### ISSUE TITLE
Lot of lag when loading terrain

### ISSUE THREAD

**Issue by pernoctador** [Zkaface/TAIGA#59]
First of all, i realy love the mod. I like a lot the expansion of tinkers. But the problem is that i can't travel with this mod anywhere. Specially the nether. The end is not too much affected as there are few ores and not too much land, but some times in the overworld and nether there is so much lag that the game almost freeze. Sometimes it doesn't even read the keys properly, thats how bad the lag is sometimes. I have confirmed that this mod is the problem because if i take it, i can play fine and if i only have it i have a lot of lag. Also, is a loading terrain problem, not a generation problem (because i have a lot of lag when i travel to places i had loaded before)

MAYBE this mod generates too many ores. It's the only thing i can think about. if you make each ore generation whithin few layers (i.e. each ore spawn between h and h+15 height, where h depends on the ore) and give options about ratio (like tinkers with cobalt) it may solve the problem a bit.

Hope it helps! i'm looking forward for any update of this mod.

**Comment by Zkaface** [comment]
@pernoctador It seems, the issue is not related to the ore generation. Of course it's the possible change of some artificial intelligence procedures... Did you recognize any issues in your console log?

**Comment by pernoctador** [comment]
no, although when i load new terrain minecraft eats all my memory, and sometimes it keeps that way for a long time. i'm doing some tests but that's all i can see

**Comment by IdleGandalf** [comment]
I have done some profiling of our WorldGen, but I found no server issues. Could we have a quick spec overview of the System you got the lags on?

I can't reproduce the high memory useage either. Do you use some other worldgen-mods as well (expect Tinkers ofc). My peak while worldgen is about 1.5 G with Tinkers and TAIGA loaded.

**Comment by pernoctador** [comment]
Isn't 1.5 pretty high? I mean you have to modify the memory heap for minecraft to run it, and it's not something everyone does. I only recall it was possible a couple of days ago. It would be great if you mention it in the instructions for the mod. 
My pc is i5, 8gb ram, Raedon R7 360 series.
With Taiga alone i only check that it needed more than 1G, so is the same you said. As for  the 2.3Gb peak, i have substratum and ic2. For the nether, substratum doesn't add anything and ic2 only adds 2 or 3 ores, and is totally playable with those and tinkers. But is pretty much imposible to play with TAIGA.

**Comment by IdleGandalf** [comment]
1.5G is not much for modded minecraft, increasing maxheap is something most people (have to) do in order to even be able to play modded minecraft with a bunch of bigger mods. Maxheap of 2-3G should do just fine and should increase performance somewhat as well. 

I haven't profiled the nether generation yet, I will check that later as well, maybe there is a performance issue hidden in nether gen, I'll check that.

Your system specs should allow you to play modded minecraft just fine, so that's not the reason either. Have you got Java 8 installed?

**Comment by IdleGandalf** [comment]
Just finished with profiling while in nether and generating new world, haven't noticed any issues either. Still don't exactly know what's causing your problem.

**Comment by pernoctador** [comment]
Well, it might be just me. I double check and yes i have the last java (both 32 and 64) and i give it 4G to java heap. With 3G in minecraft and no fancy animations or particles it works fine. I'll keep checking what it might be the issue.

**Comment by Zkaface** [comment]
Still laggy with 1.2?

**Comment by Zkaface** [comment]
closed, if there is anything broken, open a new issue!
