### ISSUE TITLE
Materials and you: Materials don't render correctly

### ISSUE THREAD

**Issue by IdleGandalf** [Zkaface/TAIGA#6]
![image](https://cloud.githubusercontent.com/assets/4494131/16974226/c0892ed0-4e3a-11e6-8dc2-9f651e7d991f.png)

**Comment by DRTR0** [comment]
@StevenTheEVILZ 

Would you mind writing your own book for now, until you get someone to help you integrate it into Tinkers? I'd love to play with the mod but I don't know what anything does. I've been playing around in Creative and understand a few things, but documentation is needed.

**Comment by StevenTheEVILZ** [comment]
@DRTR0 it's going to be implemented as soon as the developers of this mod merge the pull request (very soon I think :) ).

**Comment by DRTR0** [comment]
@StevenTheEVILZ Oh I thought you were the author. Well thank you very much for helping them. I've been wanting more metals for Tinkers for awhile now.

**Comment by StevenTheEVILZ** [comment]
@DRTR0 BTW it's just the icons, if you hover over them, it will show the name of the material, and if you click on them, it will bring you to the page with the stats of the material

**Comment by DRTR0** [comment]
@StevenTheEVILZ Did you get the modifier tool tips working in the part builder?

**Comment by StevenTheEVILZ** [comment]
? screenshot plz

**Comment by StevenTheEVILZ** [comment]
@DRTR0 ? screenshot plz

**Comment by DRTR0** [comment]
@StevenTheEVILZ You said so yourself.  I was just wondering if it were fixed. http://i.imgur.com/ZWgEHNV.png

**Comment by StevenTheEVILZ** [comment]
@DRTR0 I mean like in Minecraft

**Comment by StevenTheEVILZ** [comment]
@DRTR0 I think you mean this: https://github.com/Zkaface/TAIGA/issues/11
Zkaface said he fixed it, and it should be on github

**Comment by DRTR0** [comment]
@StevenTheEVILZ Ah, your usernames are confusing me. My bad

**Comment by StevenTheEVILZ** [comment]
@DRTR0 You mean #11 right? It's supposed to be fixed and released in the next version (I think).

**Comment by Zkaface** [comment]
Sorry, owner is on an outdoor adventure and too much drunk at this actual moment to fix anything. Next fixing session starts in about 20 hours!

**Comment by DRTR0** [comment]
@Zkaface Why was nobody else invited?

**Comment by IdleGandalf** [comment]
PR from @StevenTheEVILZ is now merged, this will be fixed in 1.0.3
