### ISSUE TITLE
Meteorite Hardness

### ISSUE THREAD

**Issue by Merthew** [Zkaface/TAIGA#61]
All of the materials that can break tier 6 hardness ores are tier 6. There is also no way to get any of the higher tier materials.

**Comment by SPMoo66** [comment]
Try making some Noctunyx, that works.

**Comment by Zkaface** [comment]
Calm down friends, 1.3 will come with a lot of material rework and a lot better balancing. Please see similar issue openings ;)

**Comment by IdleGandalf** [comment]
1.2 just got uploaded to curseforge, this is now fixed.
