### ISSUE TITLE
[1.1.4] Garishly cannot give 6 drops as intended

### ISSUE THREAD

**Issue by SPMoo66** [Zkaface/TAIGA#62]
I'm going to assume this fell through the cracks, seeing as I never got a response on this.

https://github.com/Zkaface/TAIGA/issues/53

I feel pretty confident in the results of the test I did, and I'd definitely like to know that you'll look into this at some point.

**Comment by Zkaface** [comment]
I gonna fix this in 1.2. The description seems to be wrong, there are 6 different materials which are randomly chosen to drop. Not 6 of each one! :-)

**Comment by IdleGandalf** [comment]
Fixed in the just released 1.2.
