### ISSUE TITLE
Request: dusts for the ores to allow processing of the ore via crushers, grinders, etc.

### ISSUE THREAD

**Issue by belathus** [Zkaface/TAIGA#63]
I am attempting to make a modpack that makes ore doubling tough; as such, I've removed ore doubling via the smeltery. As of right now, in my pack, there is really no other way to process TAIGA ores. I want to add custom recipes (via EnderIO's XML, ModTweaker, etc.) to grind the ores into dusts, but that cannot be done if I don't have a dust object to grind them into.

**Comment by Zkaface** [comment]
Where is the problem? Just create your own dusts organisiert isn't this possible? I also recommend to wait for 1.2

**Comment by belathus** [comment]
I'd love to create my own dusts if I had mods like AoBD, Tabula Rasa, or Otho's Metamod (Custom Items). As far as I am aware, there aren't any custom item mods available for 1.10.2 yet.

**Comment by Zkaface** [comment]
@belathus The main Problem I see is: If I create dusts, I have no use for them. When I'm ready with 1.3 I gonna plan to create some items... just to "have" them!

**Comment by belathus** [comment]
That's fair. It'd just be nice to be able to process these ores via other mods.

**Comment by Zkaface** [comment]
@belathus If you are fluent in coding Java, you are probably able to ask the modders if their mods are designed to automatically integrate other materials. Like if they are oredicted with dust, ore, bars and blocks or so. This also takes a lot more time, if they do not have any kind of automatic integration. Let's see what the future holds.

**Comment by Zkaface** [comment]
So, dusts are coming in the next minor update 1.2.1!

**Comment by belathus** [comment]
Yay! Hah. They'll be nice to have for other mods. I appreciate your work.

**Comment by Zkaface** [comment]
Hello @belathus, do all the dusts work for this moment?

**Comment by HellishINC** [comment]
I'm not sure where 1.2.1 was released (it's not on curseforge at the time of writing) so I went ahead and compiled the source.

Actually Aditions appears to see and properly use/create dusts though I have not tested all of them.

**Comment by Zkaface** [comment]
@HellishINC Maybe check 1.2, i created the dusts earlier. But I am not sure if they work like you expected. Please give me some feedback :-)

For 1.2.1 it took me longer than expected, just because my newborn son made a lot of work ;-)

**Comment by HellishINC** [comment]
Is there any possibility to have support for Mekanism's 5x ore processing?

**Comment by Zkaface** [comment]
@HellishINC If mechanism takes the oredict for its processing, then yes. What does mekanism need for the process?

**Comment by MineWitherMC** [comment]
@Zkaface for 4x it will be easy (shard*, chunk*, dustDirty* if I'm correct). For 5x it isn't that hard too but it uses liquids (or probably even gases?) for the beginning and I'm not sure you can OreDict gases/fluids.

**Comment by Zkaface** [comment]
That sounds a bit complicated :-D are cobalt and ardite included? Because they do not have chunk and dirty dust items.

**Comment by MineWitherMC** [comment]
@Zkaface they aren't, in vanilla Mk only Vanilla, Mk, lead and silver do exist

**Comment by Zkaface** [comment]
Suggestion: Aks the author of mekanism, if his or her mod automatically works with oreDict entries. If so, I implement them. In that case i need to know, how these extra items look :)

**Comment by IdleGandalf** [comment]
https://github.com/aidancbrady/Mekanism/wiki/IMC-based-recipe-integration

**Comment by Zkaface** [comment]
@MineWitherMC 
I close this for now, because the issue was a request for dusts. Please open a separate issue for mekanism, if desired
