### ISSUE TITLE
[1.2] Lots of missing localization

### ISSUE THREAD

**Issue by SephirothWS** [Zkaface/TAIGA#65]
Load up TAIGA with Tinkers' Construct 2.6.0 in Minecraft 1.10.2
Load up JEI as well.

Search @TinkersAlloy in JEI to show only items added by this mod.

Mouseover them.

Notice how more than 50% of the entries in JEI follow the format item|block|fluid.something.name

Realize how limited the localization in EN-US is and face-palm.

Open the Tinkers' Book and begin looking at the tooltips of the new traits added by the mod. Some simply don't exist in the localization file. Others. ... well, linebreaks need to be implemented *properly*.

![Image](https://i.imgur.com/QWDHJRd.png)
![Image](https://i.imgur.com/KMWteIq.png)

**Comment by Zkaface** [comment]
@SephirothWS You've even read the release notes? I want to clean out bugs, need input for traits and did not focus on naming stuff. It's just a beta! So please, show us some respect and not this facepalm bs!

**Comment by SephirothWS** [comment]
And this kind of bullshit responses is why sometimes you don't even GET the feedback you'd like. This is an issue, sure it's apparently low on your schedule, but it is an issue nonetheless.
