### ISSUE TITLE
crash on start up something about bow materials.

### ISSUE THREAD

**Issue by mattattack444** [Zkaface/TAIGA#66]
[crashofdoooooooom.txt](https://github.com/Zkaface/TAIGA/files/637155/crashofdoooooooom.txt)

**Comment by IdleGandalf** [comment]
I think you need latest tinkers (2.6) to use TAIGA 1.2, since the bow stuff was brought back in 2.6.

**Comment by mattattack444** [comment]
ah ok ill have a looksee :) thought i was running the latest tinkers haha. cheers :)

**Comment by IdleGandalf** [comment]
Yea see if 2.6 solves your problem, otherwise we'll have a closer look.

**Comment by Zkaface** [comment]
closed as of version 2.6 should solve the problem. If any other issues come up, feel free to open another issue :)
