### ISSUE TITLE
Blocks won't melt or be crafted into ingots

### ISSUE THREAD

**Issue by Cheezy16** [Zkaface/TAIGA#69]
I tried to melt a Vibranium block in the smeltery, and it said that it was not hot enough to melt the block, so  is this a bug or is there some fuel that I'm missing?

**Comment by Zkaface** [comment]
@Cheezy16 What a bug. The first major bug. Thx for your help! Will fix this soon!

**Comment by Zkaface** [comment]
Fixed in next update!
