### ISSUE TITLE
Question: End Generation

### ISSUE THREAD

**Issue by Cheezy16** [Zkaface/TAIGA#70]
So I went to the End to get some palladium for lumix, and when I generated new chunks all I found was little scattered chunks of endstone, about 5-10 in a chunk, spread everywhere, but I did still find the obsidirite and uru ore cubes. I want to know if this is a generation bug or if its just because I have a pre-1.2 world...

**Comment by Zkaface** [comment]
@Cheezy16 For palladium you have to search some time. It's rare and deeper in the lands. Try to find the Teleporter to the Outlands of the end dimension. 

I try to upload everything tomorrow, but I am busy atm too

**Comment by Cheezy16** [comment]
Ok, I'll look deeper then, thanks!

**Comment by Zkaface** [comment]
@Cheezy16 Not too deep. At the lowest levels you gonna find some other ore ;-)

**Comment by Zkaface** [comment]
@Zkaface If you have a better idea for spawning ores, please tell me :-) I think there could be more creativity in the general generation... Like the meteors, the lowest level ores of end and the lava ores in the nether.

**Comment by Zkaface** [comment]
@Cheezy16 The overworld meteors are spherical, but I wanted to have special ones in the end. Of course I try to generate some code for more meteor-alike ones. 

Pictures... Hmm just upload em with imgur and place the links in here 👍

**Comment by Zkaface** [comment]
@IdleGandalf And about the little endstone chunks. They are intended for having some anchor points to get to flying meteorites without the ability of flying :-)

**Comment by Cheezy16** [comment]
Ok, I get the endstone chunks bit. That makes sense, but are the end islands all gone, or are they just spaced out?

**Comment by Cheezy16** [comment]
![2016-12-10_11 35 32](https://cloud.githubusercontent.com/assets/24446092/21075103/cb309b94-bed7-11e6-8026-8f32c2b43eec.png)

**Comment by Zkaface** [comment]
@Cheezy16 They are far away, that's vanilla coded. If you kill the ender dragon, there is spawning a small portal randomly, where you have to throw a ender pearl to reach it.

**Comment by Cheezy16** [comment]
![end-outer-islands](https://cloud.githubusercontent.com/assets/24446092/21075119/1cdcfa1e-bed8-11e6-8597-7db16da1661d.png)
But they usually end up like this though..?

**Comment by Zkaface** [comment]
@Cheezy16 Isn't that like always? I'm not sure at the moment. These additional ender islands are still floating and roughly connected.

**Comment by Cheezy16** [comment]
Nvm, I went further on just by flying through and I see it didn't change the outer islands, my mistake.

**Comment by Zkaface** [comment]
@Cheezy16 Okay, if you find anything else, which should not be, let us know!
