### ISSUE TITLE
[1.2] Cannot toggle off new ore generation

### ISSUE THREAD

**Issue by belathus** [Zkaface/TAIGA#71]
I've disabled all ore generation in TAIGA's config, but we're getting the large meteors, as well as some other ore generation.

**Comment by Zkaface** [comment]
@belathus I noticed this issue by myself and this is fixed on the next small update. Please be patient, I plan to release today evening (middle European time).

**Comment by belathus** [comment]
No problem, @Zkaface. I was just pointing it out in case you weren't already aware.

**Comment by Zkaface** [comment]
@belathus Thx mate :-)

**Comment by Divineaspect** [comment]
We could really use this.

**Comment by Zkaface** [comment]
At this moment I struggle with some issues in ore generation. When this is done, i set the focus on a better config! Sorry for any inconvenience

**Comment by Zkaface** [comment]
Should be fixed in 1.2.1
