### ISSUE TITLE
Please consider removing the Curvature teleportation effects

### ISSUE THREAD

**Issue by StevenTheEVILZ** [Zkaface/TAIGA#8]
Sorry, not really an issue, more of an enhancement, kinda a balancing thing.

**Comment by Zkaface** [comment]
Can you tell me the reason? Of yourse I will implement a config to set the radius and/or an activation of the teleportation.

**Comment by StevenTheEVILZ** [comment]
Originally, I was experimenting with Astrium, then I noticed that I would get teleported to random places while fighting mobs. I though it was a game glitch. After a while of looking around, I found that my tool had a modifier called curvature, but the description was broken. So I went in to the source code and found the description. My concern is that the teleportation effect makes the tool unusable due to the random teleportation. My other concern is the Botania. There is one boss that keeps you inside certain boundaries, and teleportation might screw that up (have not tested it yet). I also failed to find the config file (not sure if there is one). But all that said, a config option to turn it off or to adjust the settings will be AMAZING.

**Comment by StevenTheEVILZ** [comment]
Also, this might not be the place to post this, but can you add enderium with all its OP glory (the compat part might be a bit tedious, but I'm willing to help)?

**Comment by Zkaface** [comment]
The description will be put in in 1.0.3. The Config of course in 1.0.3 or 1.0.4, depends how far I get the mod today.

Enderium and OP glory? I'm open for ideas, please tell me, I'm not sure what was the conclusion about it in 1.7.10.

To teleportation: It's made for a chance of escaping but with a focus on a negative factor in battle. Have to think about it, what to use instead of this... I still need more trait-ideas!

**Comment by StevenTheEVILZ** [comment]
A good idea might to have the user and the target swap places in battle.

**Comment by Zkaface** [comment]
Haha, thank you. Great Idea. This will be implemented!
If you have more ideas, I am always open for more traits :)

**Comment by StevenTheEVILZ** [comment]
K :)
about the enderium, if that is "too OP", then please implement less OP version of it. Substratum adds it, and I would like to see it used somewhere.

**Comment by Zkaface** [comment]
Please tell me about it. What should it do?

**Comment by StevenTheEVILZ** [comment]
Since enderium is relatively easy to get, I suggest a medium-low durability, low mining level, high attack and medium mining speed, possibly an extra modifier (kinda like thaumium), and possible even some teleportation like effect closer to the original curvature than the new proposed one.

**Comment by Zkaface** [comment]
It was made from ender eyes?

**Comment by StevenTheEVILZ** [comment]
ender pearls, silver, platinum, and tin

**Comment by Zkaface** [comment]
Ok - atm i have no silver nor platinum implemented, but some other blocks, which could be the prefered material.

**Comment by StevenTheEVILZ** [comment]
What does "preferred material" mean? And also, other mods have the recipe implemented (EnderIO and Substratum). A lot of the mods don't implement their metals and ores to be smelted in the smeltery, and as of right now, there is no mod like ExtraTiC doing that in 1.10. Unfortunately, those mods include EnderIO and Substratum. This might take a while, but it would be worthwhile to implement all those mods and add compatibility, especially with Substratum. A good way to do this would be to have the stats in a json file and have the mod just check for an oreDict entry and add molten X and X tool rod and so on. I can help with that. But unfortunately, it would not be wise th change the recipe for enderium as other mods have already added enderium but don't use it.

**Comment by Zkaface** [comment]
Hm...Yeah, the problem is, that 16 additional metal-ores are a lot atm. And I have no idea, how long it would take to build more around it. If the mod will be out of it's kid shoes and most features are running free of issues, I am willing to put more content in - Especially functionality and connections to other mods like EnderIO and / or Substratum. And this will also be depending to these other mods. If they are not running properly, my mod properly properly won't work well.

Preferred material: I have 2 or 3 blocks, which are just implemented for a cosmetic intent atm (as a placeholder)

**Comment by StevenTheEVILZ** [comment]
Tell me if I'm correct: you want to implement a recipe for enderium and a means to create it using only your mod? I think it would be better to just check for its implementation by other mods, and add it if it's their. If you want to, you don't even have to add support the recipe in the smelter (even though the recipe would be quite awesome).

**Comment by StevenTheEVILZ** [comment]
Also, I can help write the json with the metals and stuffs.

**Comment by Zkaface** [comment]
yeah, why not. Look through the code, and make a pull request, if it's working properly :+1: 

to enderium: no no no, I just were thinking loud about it ;) there shouldn't be 2 recipes for the same result.

**Comment by StevenTheEVILZ** [comment]
K, will get started soon.

**Comment by StevenTheEVILZ** [comment]
Also, some further documentation of your code would be good :).

**Comment by Zkaface** [comment]
-> write to me StevenTheEvil@sosnitzka.com

**Comment by StevenTheEVILZ** [comment]
that's an email?

**Comment by Zkaface** [comment]
yes, ^^hurry up
