### ISSUE TITLE
Will upgrading destroy my world?

### ISSUE THREAD

**Issue by Zarepheth** [Zkaface/TAIGA#82]
Will upgrading from TAIGA 1.1.3 to 1.2.1 damage my existing worlds?
Forge warned me about 204 missing blocks when I attempted the upgrade, so I'm wondering if the new version has numerous blocks and entities removed or if the mapping between blocks and block IDs has changed.

**Comment by Zkaface** [comment]
There are a lot of changes blocks, so most of the old taiga blocks will be replaced. I apologize for these problems, but the creation of this mod ran through a big process of creative issues. You should make a backup and see what is happening and if you are pleased or disappointed. 

Best wishes for christmas!

**Comment by Divineaspect** [comment]
Yes

**Comment by Zarepheth** [comment]
Thanks for the warning. I'll stay at 1.1.3 until I'm ready to start another world.

**Comment by Flabort** [comment]
These are the ores and alloy recipes in 1.2.1:
http://imgur.com/gallery/xiALr

**Comment by Zkaface** [comment]
@Flabort Awesome flowchart by the way 🥇
