### ISSUE TITLE
Missing Texture(s) in Materials And You, as well as JEI

### ISSUE THREAD

**Issue by Flabort** [Zkaface/TAIGA#83]
Terrax is shown as the purple and black block in the Tinker's Guide.
I personally think it's amazing that this version of Tinkers can automatically fill in the book with materials like this, but this material from the mod doesn't work.

Tested on a world with nothing but Tinkres, Mantle, and TAIGA. (Have not tested the new version's compatibility with other mods yet)

**Comment by Flabort** [comment]
I may as well document all issues with the Materials and You book at the moment. Mostly just typos.

1) Tiberium: "is" ist misspelled
2) Vibranium: Resonance: has a "/" and no linebreak in it's tooltip.
3) Terrax: As mentioned, the ingot has no texture.
4) Mining levels: The text for the new mining levels is the same color as the page behind them.

**Comment by Flabort** [comment]
When viewing recipes to make Jauxum fluid in JEI (which I added to see alloy recipes), all textures are broken. Same with Ovium and Terrax.

**Comment by Zkaface** [comment]
Issues should be fixed in next update.
