### ISSUE TITLE
Let Basalt from other mods be used if it exists.

### ISSUE THREAD

**Issue by Flabort** [Zkaface/TAIGA#84]
There is another mod which creates basalt in world generation. 
How about have it look to see if quark:basalt exists already, and if it does make the recipes to melt it down etc use the quark basalt instead?

**Comment by Zkaface** [comment]
The Problem is, that this basalt will spawn at other places. Of course I have to rename that material at internal registration... I am not sure at the moment.

**Comment by Syndaryl** [comment]
Two options: 
add an option disable world generation of your own basalt if quark basalt is available
contact vasili and ask him to add a feature to disable world generation of his own basalt if yours is available (he does these sorts of things).

In either case, if both of you put your basalt in the oredict, it should be easy to share them in recepies. If Quark's basalt isn't oredicted yet, I'm sure you could put in a feature request for it.

**Comment by Zkaface** [comment]
I gonna check, whats going on, when his Basalt is included. Of course I put a feature in to rename my basalt to something similar - i do not want to take out his basalt, nor want I to exclude mine ;) Let's see what I can find out!

**Comment by IdleGandalf** [comment]
What @Flabort means it that he can use the other basalt in our recipes as well, its not about interfering with other basalt types.

**Comment by ruyanve** [comment]
The way Quark generates basalt is generated makes it a viable building material and most of my players make heavy use of it. I would rather keep them separated and consider a name change, so it keeps it's rarity.

**Comment by Zkaface** [comment]
@ruyanve Is it registered with an valuable ore registry name? Like blockBasalt or oreBasalt? In that case it needs to be renamed

**Comment by ruyanve** [comment]
Quark Basalt is registered as stoneBasalt

**Comment by Zkaface** [comment]
@ruyanve There should not be a problem in that case, because the smelting is registered as blockBasalt

**Comment by ruyanve** [comment]
Hm ok... But that would still leave the issue of rarity, wouldn't it? Quark Basalt is rather easy to find and quite abundant, while TAIGA Basalt seems to be more rare and therefore valuable, or am I overthinking here? :-P

**Comment by Zkaface** [comment]
@ruyanve Are you able to smelt that Basalt in a smeltery?

**Comment by IdleGandalf** [comment]
Nah, ofc not. These is no need for action here.

**Comment by ruyanve** [comment]
Confirmed, it won't smelt. So we are left with two different blocks with the same name then? Easy fix for me would be to modify the lang file I assume?

**Comment by IdleGandalf** [comment]
@ruyanve You could do that yes. Maybe @Zkaface decides to rename the block officially in one of the next releases, thats up to him.

**Comment by ruyanve** [comment]
Considering the popularity of Quark, I highly recommend doing so, to avoid confusion and further requests like the one here. ;-)
Thanks guys, so far everyone like the new version of TAIGA a lot on my server, especially since the first version was a little pita. The way you are on right now feels more like quality > quantity and that's always a good thing! Keep it up <3

**Comment by Zkaface** [comment]
@ruyanve Thank you for your help and request. It helps me to make it even better.
