### ISSUE TITLE
Materials don't display their attributes in the part builder

### ISSUE THREAD

**Issue by Tenebris11** [Zkaface/TAIGA#9]
Materials don't seem to display their attributes in the part builder.  That makes it difficult to choose how to use each material most effectively.

**Comment by Zkaface** [comment]
You mean in the tool forge?

**Comment by Zkaface** [comment]
Oh, I see what you mean. I gonna look for a solution. It should be displayed, yep.

**Comment by Zkaface** [comment]
In 1.0.3 it'll be fixed
